### ISSUE TITLE
What's Issue 42?

### ISSUE THREAD

**Issue by imaginary-person** [malloc-42/malloc-42.github.io#2]
What's this blog about? What's Issue 42? Just curious

**Comment by kshitij12345** [comment]
Hi @Imaginary-Person, thanks for showing interest!

We are just a group of open source enthusiasts/developers who decided to work together on things we don't know yet and want to learn, or find certain things to be worth explaining and sharing with the world. Since we just started, so things are still in initial stage.

We plan to write blogs/create videos on our YouTube channel/do projects on GitHub, and this mainly depends on what the idea demands. If there is something worth writing a blog about, we are motivated to do that. Similarly for YouTube channel as well as GitHub organization.

On your question about Issue 42, I know you must be aware of what it is, but just quoting Wikipedia here:

>  The number 42 is, in The Hitchhiker's Guide to the Galaxy by Douglas Adams, the "Answer to the Ultimate Question of Life, the Universe, and Everything," calculated by an enormous supercomputer named Deep Thought over a period of 7.5 million years. Unfortunately, no one knows what the question is.

Refernce: https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker's_Guide_to_the_Galaxy

The name malloc(42) comes from the same, we are trying to allocate memory to the solution of everything. And while we do that, we hope to find what the question was! :wink: This is just a word game, technically - we are here to share with the world on whatever we know but we don't stop there - we pick up things we don't know yet - learn them - discuss - maybe build projects on the top of them and while we are doing this - we don't mind sharing it with the world. :heart:

I appreciate that you asked, and I hope this answered your question. If this sounds interesting to you, and if you are interested in contributing with us together, or have any queries - we can always connect and discuss! We will be more than happy to hear from you.

Also, me and @krshrimali (who actually drafted this reply.Thanks :) ) have followed your great work on contributing for PyTorch. Keep it up! :clap:

Thanks again for reaching out. In our imagination, we do like to believe that @imaginary-person is keeping well, and we hope for the same. :slightly_smiling_face: 

Thanks!

**Comment by imaginary-person** [comment]
Thanks for your response! 😃 
I was aware of The Hitchhiker's Guide to the Galaxy reference of 42, but it didn't strike me then.
I hope you guys are also keeping well.
